import type {NextPage} from "next"
import Head from "next/head"
import {useState, useEffect} from "react"
import * as fcl from "@onflow/fcl"
import useUtils from "../utils/index.mjs"
import useHooks from "../hooks/index.mjs"

type TechnologyCardProps = {
  name: string
  description: string
  website: string
  auth: () => void
}

const Home: NextPage = () => {
  const [walletServices, setWalletServices] = useState<fcl.WalletService[]>([])
  const util = useUtils()
  const hooks = useHooks()
  const config = hooks.useConfig()
  console.log(config)

  useEffect(() => {
    const fetchServices = async () => {
      await fcl.discovery.authn.subscribe(res => {
        setWalletServices(res.results)
      })
    }
    setTimeout(() => {
      fetchServices()
    }, 0)
  }, [])

  const login = async () => {
    // prettier-ignore
    await fcl
    .logIn()
    .then(util.yup("Authn"))
    .catch(util.nope("Authn"))
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto flex flex-col items-center justify-center min-h-screen p-4'>
        <h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
          Create <span className='text-purple-300'>T3</span> App
        </h1>
        <button onClick={login}>Login</button>
        <button onClick={() => fcl.unauthenticate()}>Logout</button>

        <p className='text-2xl text-gray-700'>This stack uses:</p>
        <div className='grid gap-3 pt-3 mt-3 text-center md:grid-cols-3 lg:w-2/3'>
          {walletServices?.map(
            ({uid, provider: {name, description, website}}) => (
              <TechnologyCard
                key={uid}
                name={name}
                description={description}
                website={website}
                auth={login}
              />
            )
          )}
        </div>
      </main>
    </>
  )
}

const TechnologyCard = ({
  name,
  description,
  website,
  auth,
}: TechnologyCardProps) => {
  return (
    <section className='flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105'>
      <h2 className='text-lg text-gray-700' onClick={auth}>
        {name}
      </h2>
      <p className='text-sm text-gray-600'>{description}</p>
      <a
        className='mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2'
        href={website}
        target='_blank'
        rel='noreferrer'
      >
        Website
      </a>
    </section>
  )
}

export default Home
